name: heroku-deploy

on:
  push:
    branches: 
    - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - name: Config Flutter
      run: |
        flutter config --enable-web
        cd frontend && flutter pub get
    - name: Build app
      run: cd frontend && flutter build web --release
    
    - name: Move frontend
      run: |
        mv -v frontend/build/web/* static/
        mv -v static/assets/assets/* static/assets/
        rm -rf frontend
      
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "staysia"
        heroku_email: "tanishbafna03@gmail.com"
